name: Alipay Cloud Devops Codescan
on:
  push:
      branches: [ master ]
  pull_request:
     branches: [ master ]
  #pull_request_target: 
jobs:
  stc:
    runs-on: ubuntu-latest
    steps:
      - name: codeScan
        uses: huqiuxiang/alipay-cloud-devops-codescan@new_stc_xihuan
        with:
          parent_uid: ${{ secrets.ALI_PID }}
          private_key: ${{ secrets.ALI_PK }}
          scan_type: stc
  sca:
    runs-on: ubuntu-latest
    steps:
      - name: codeScan
        uses: huqiuxiang/alipay-cloud-devops-codescan@new_stc_xihuan
        with:
          parent_uid: ${{ secrets.ALI_PID }}
          private_key: ${{ secrets.ALI_PK }}
          scan_type: sca
